name: Deploy Orchestrator

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

permissions:
  id-token: write        # REQUIRED for Azure OIDC
  contents: read         # REQUIRED for checkout + OIDC

jobs:
  orchestrator:
    uses: ./.github/workflows/Shared-Deploy.yml
    with:
      resourceGroup: rg-orchestrator
      location: canadacentral
      templateFile: Spoke/Orchestrator.bicep
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}