name: Shared Bicep Deployment

on:
  workflow_call:
    inputs:
      resourceGroup:
        required: true
        type: string
      location:
        required: true
        type: string
      templateFile:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
    outputs:
      deploymentOutput:
        description: "Outputs from the Bicep deployment"
        value: ${{ jobs.deploy.outputs.deploymentOutput }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest